services:
  app:
    image: todo-frontend-dev
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api
    container_name: todo-frontend-dev

  nginx:
    image: nginx:1.29-alpine
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server

  server:
    image: todo-backend-dev
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-backend:/usr/src/app

    environment:
      - REDIS_URL=//redis:6379
      - MONGO_URL=mongodb://root:example@mongo:27017
    container_name: todo-backend-dev
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes: 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo-data:/data/db

  redis:
    image: redis
    command: ['redis-server', "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  mongo-data:
  redis_data: