services:
  app:
    image: bloglist-frontend-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    container_name: bloglist-frontend-dev

  nginx:
    image: nginx:1.29-alpine
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: bloglist-reverse-proxy
    depends_on:
      - app
      - server

  server:
    image: bloglist-backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    container_name: bloglist-backend-dev